homework5: Factory Class Reference
Factory Class Reference
Класс Factory это фабрика объектов для созданиия разных вариаций графических юнитов
#include <fabric.h>
Public Member Functions
AbstractGraphicUnit_ptr createUnit (int index, int x=0, int y=0, std::string name="")
Создание графического юнита с заданным индексом
std::list< std::pair< int, std::string > > get_unit_types ()
Получить перечень всех возможных юнитов с индексами и текстовыми описаниями
int registrate (AbstractGraphicUnit_ptr unit, std::string description)
регистрация нового типа юнита для использования фабрикой
Static Public Member Functions
static Factory * getInstance ()
Private Member Functions
Factory ()
Factory (Factory &other)
Factory & operator= (Factory &other)
~Factory ()=default
Static Private Attributes
static Factory * m_Factory =nullptr
Detailed Description
Класс Factory это фабрика объектов для созданиия разных вариаций графических юнитов
Представляет собой синглтон (указатель на фабрику доступен по вызову статической функции getInstance())
Всем поддерживаемым типам юнитов соответствует определенный индекс
Definition at line 13 of file fabric.h.
Constructor & Destructor Documentation
Factory() [1/2]
Factory::Factory () inline private
Definition at line 16 of file fabric.h.
               {
         //TODO реализовать конструктор
     }
Referenced by getInstance().
Factory() [2/2]
Factory::Factory (Factory & other) inline private
Definition at line 19 of file fabric.h.
 {}
~Factory()
Factory::~Factory () private default
Member Function Documentation
createUnit()
AbstractGraphicUnit_ptr Factory::createUnit (int index, int x = 0, int y = 0, std::string name = "") inline
Создание графического юнита с заданным индексом
Parameters
параметр index типа int- индекс юнита на фабрике
параметр x типа int- координата x юнита.
параметр y типа int- координата y юнита.
параметр name типа std::string - имя юнита.
Returns
указатель типа AbstractGraphicUnit_ptr на созданный юнит
Definition at line 36 of file fabric.h.
{
         //TODO реализовать метод
     }
Referenced by Document::addUnit().
get_unit_types()
std::list<std::pair<int, std::string> > Factory::get_unit_types () inline
Получить перечень всех возможных юнитов с индексами и текстовыми описаниями
Returns
список типа std::list<std::pair<int, std::string>> содержащий пары вида: индекс/описание элемента
Definition at line 45 of file fabric.h.
{
         //TODO реализовать метод
     }
Referenced by Document::get_unit_types().
getInstance()
static Factory* Factory::getInstance () inline static
Definition at line 23 of file fabric.h.
{
         if (!m_Factory) m_Factory=new Factory;
         return m_Factory;
     }
Referenced by main().
operator=()
Factory& Factory::operator= (Factory & other) inline private
Definition at line 20 of file fabric.h.
 {}
registrate()
int Factory::registrate (AbstractGraphicUnit_ptr unit, std::string description) inline
регистрация нового типа юнита для использования фабрикой
Parameters
параметр unit типа AbstractGraphicUnit_ptr - юнит для регистрации на фабрике
параметр description типа std::string - описание нового юнита.
Returns
индекс полученный данным типом юнитов при регистрации
Definition at line 56 of file fabric.h.
{
         //TODO реализовать метод
     }
Member Data Documentation
m_Factory
Factory* Factory::m_Factory =nullptr inline static private
Definition at line 15 of file fabric.h.
Referenced by getInstance().
The documentation for this class was generated from the following file:
fabric.h