homework5: Model Class Reference
Model Class Reference
Класс Model предназначен для работы с системой хранения (с файлами)
#include <model.h>
Public Member Functions
std::list< AbstractGraphicUnit_ptr > load_from_file (std::string filename)
Загрузить данные из файла
void save_to_file (std::string filename, std::list< AbstractGraphicUnit_ptr > list)
Сохранить данные в файл
Static Public Member Functions
static Model * getInstance ()
Private Member Functions
Model ()
Model (Model &other)
Model & operator= (Model &other)
~Model ()=default
Static Private Attributes
static Model * m_model =nullptr
Detailed Description
Класс Model предназначен для работы с системой хранения (с файлами)
Представляет собой синглтон (указатель на модель доступен по вызову статической функции getInstance())
Definition at line 12 of file model.h.
Constructor & Destructor Documentation
Model() [1/2]
Model::Model () inline private
Definition at line 15 of file model.h.
            {
         //TODO реализовать конструктор
     }
Referenced by getInstance().
Model() [2/2]
Model::Model (Model & other) inline private
Definition at line 18 of file model.h.
 {}
~Model()
Model::~Model () private default
Member Function Documentation
getInstance()
static Model* Model::getInstance () inline static
Definition at line 22 of file model.h.
{
         if (!m_model) m_model=new Model;
         return m_model;
     }
Referenced by main().
load_from_file()
std::list<AbstractGraphicUnit_ptr> Model::load_from_file (std::string filename) inline
Загрузить данные из файла
Parameters
параметр filename типа std::string - имя файла
Returns
список типа std::list<AbstractGraphicUnit_ptr> содержащий указатели на юниты
Definition at line 32 of file model.h.
{
         //TODO загрузить данные из файла
     }
Referenced by Document::loadFromFile().
operator=()
Model& Model::operator= (Model & other) inline private
Definition at line 19 of file model.h.
 {}
save_to_file()
void Model::save_to_file (std::string filename, std::list< AbstractGraphicUnit_ptr > list) inline
Сохранить данные в файл
Parameters
параметр filename типа std::string - имя файла
список типа std::list<AbstractGraphicUnit_ptr> содержащий указатели на юниты
Definition at line 42 of file model.h.
{
         //TODO сохранить данные в файл
     }
Referenced by Document::saveToFile().
Member Data Documentation
m_model
Model* Model::m_model =nullptr inline static private
Definition at line 14 of file model.h.
Referenced by getInstance().
The documentation for this class was generated from the following file:
model.h